name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Docker Publish"]  # Le nom du workflow qui build et push l'image Docker
    types:
      - completed  # Déclenche ce workflow lorsque l'autre est terminé avec succès

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Docker container to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            # Arrêter le conteneur existant s'il y en a un
            docker stop fastapi-crm || true
            docker rm fastapi-crm || true
            
            # Télécharger la dernière version de l'image Docker
            docker pull lucaszub/fastapi-crm:latest

            # Lancer le conteneur avec le port 80 exposé
            docker run -d --name fastapi-crm -p 80:80 lucaszub/fastapi-crm:1.0.13

            echo "Déploiement terminé avec succès !"
          EOF
