jobs:
  setup-ssl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Install and configure SSL
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} <<EOF
            set -e

            # Mettre à jour et installer les dépendances
            sudo apt-get update
            sudo apt-get install -y nginx certbot python3-certbot-nginx

            # Démarrer et activer Nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx

            # Obtenir le certificat SSL
            sudo certbot --nginx -d lzubdev.com -d www.lzubdev.com --non-interactive --agree-tos -m zubiarrainlucas@gmail.com --redirect

            # Désactiver la configuration par défaut
            sudo rm -f /etc/nginx/sites-enabled/default

            # Créer la configuration Nginx pour lzubdev.com
            if [ ! -f /etc/nginx/sites-available/lzubdev.com ]; then
              sudo bash -c 'cat > /etc/nginx/sites-available/lzubdev.com <<EOF_CONF
server {
    listen 80;
    server_name lzubdev.com www.lzubdev.com;

    # Redirection HTTP vers HTTPS
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    server_name lzubdev.com www.lzubdev.com;

    ssl_certificate /etc/letsencrypt/live/lzubdev.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lzubdev.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://localhost:8000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF_CONF'
            fi

            # Activer la configuration
            sudo ln -sf /etc/nginx/sites-available/lzubdev.com /etc/nginx/sites-enabled/

            # Vérifier la syntaxe de Nginx
            sudo nginx -t

            # Recharger Nginx pour appliquer les changements
            sudo systemctl reload nginx

            # Redémarrer FastAPI (adapte cette commande selon ton gestionnaire de processus)
            sudo systemctl restart my_fastapi_app.service || echo "FastAPI app service not found."

            echo "SSL et configuration Nginx complétés avec succès!"
EOF
